### ISSUE TITLE
Could the relationship between covariant / contravariant / invariant functors be a little more fine-grained?

### ISSUE THREAD

**Issue by dalaing** [nfrisby/invariant-functors#14]
Should the instances
```
(Invariant f, Invariant g) => Invariant (ComposeFC f g)
(Invariant f, Invariant g) => Invariant (ComposeCF f g)
```
be
```
(Functor f, Contravariant g) => Invariant (ComposeFC f g)
(Contravariant f, Functor g) => Invariant (ComposeCF f g)
```
instead?

This would possibly lead to some additional newtypes to handle all of the other combinations of covariant / contravariant / invariant functors that can be composed to form an invariant functor:
```
ComposeFI
ComposeIF
ComposeIC
ComposeCI
ComposeII
```

I'm happy to do this work - and I have usages in mind for all (or at least most) of this - I just wanted to check if it was a welcome change before I got stuck in.

**Comment by RyanGlScott** [comment]
Hm, perhaps so. I didn't have a particular rhyme or reason in mind when writing those instances—I just wanted to have an instance for everything from the `contravariant` library, and that's what resulted :)

I think your proposed redesign sounds reasonable.

**Comment by dalaing** [comment]
Gah, I wasn't actually thinking of Compose, I was thinking of Product.  With that search and replace I'm happy.  This is for doing things like [this](https://gist.github.com/dalaing/4ff035b1e355f66eedf873e6168c0f20) - and way beyond...

**Comment by dalaing** [comment]
I'll work something up in a PR and see what people think.

**Comment by RyanGlScott** [comment]
`Product` as in `Data.Functor.Product`?

**Comment by RyanGlScott** [comment]
In that case, I'm not so sure anymore. When creating these instances, I took the general approach of using `Invariant` in place of `Functor`/`Contravariant` as much as possible. You could conceivably take many of these `Invariant` instances and replace them with `Functor`/`Contravariant` in certain places, but then you'd need a positively _enormous_ number of newtypes to support every pairwise combination.

`ComposeFC`/`ComposeCF`/_et al._ is a bit of a special case, since it actually has the classes in its name. But for other data types, I think I'd prefer to keep `Invariant` contexts wherever possible.

Moreover, I'm not sure I'd want to have newtypes for every possible configuration—if we added them for `Product`, then it seems odd that we wouldn't have them for _every_ data type in the same pedigree.

**Comment by dalaing** [comment]
That's fine - if I'm writing a bunch of newtypes and they don't overlap too much with existing newtypes, I don't mind creating them somewhere else.  Sorry for the noise :)
